language: node_js
cache: yarn
node_js:
  - node
  - 10

# Fix for: error fsevents@2.1.2: The platform "linux" is incompatible with this module.
install: skip

script:
  # Fix for: error fsevents@2.1.2: The platform "linux" is incompatible with this module.
  - npx json -I -f package.json -e 'this.resolutions={}'
  - yarn
  - yarn test
